SistemaPracticasAcademicas/Areas/Admin/Models/ViewModels/DocenteViewModel.cs
using SistemaPracticasAcademicas.Models;
using System.Collections.Generic;

namespace SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels
{
    public class DocenteViewModel
    {
        public Usuario Usuario { get; set; }
        public IEnumerable<Division> Divisiones { get; set; }
        public IEnumerable<Role> Roles { get; set; }
    }
}

SistemaPracticasAcademicas/Areas/Admin/Controllers/DocentesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels;
using SistemaPracticasAcademicas.Areas.Repository;
using SistemaPracticasAcademicas.Models;
using System.Linq;
using System.Text.RegularExpressions;

namespace SistemaPracticasAcademicas.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class DocentesController : Controller
    {
        public sistema_academicoContext Context { get; }

        public DocentesController(sistema_academicoContext _context)
        {
            Context = _context;
        }
        public IActionResult Index(string buscar)
        {
            DocentesRepository _repo = new(Context);
            
            var _entity = _repo.GetAllPersonal();
            if (string.IsNullOrWhiteSpace(buscar))
                return View(_entity);
            else
                return View(_repo.SearchPersonalByString(_entity, buscar));
                //return View(_entity.Where(n=>n.Nombre.ToUpper().Contains(id.ToUpper())));
        }
        public IActionResult Agregar()
        {
            DocenteViewModel _docenteVM = new();
            DocentesRepository _repo = new(Context);
            DivisionesRepository _repoDivision = new(Context);

            _docenteVM.Divisiones = _repoDivision.GetDivisiones();
            if (User.IsInRole("Administrador"))
                _docenteVM.Roles = _repo.GetAllRoles();
            else
                _docenteVM.Roles = _repo.GetRolDocente();
            return View(_docenteVM);
        }
        [HttpPost]
        public IActionResult Agregar(DocenteViewModel _docenteVM)
        {
            DocentesRepository _repo = new(Context);
            DivisionesRepository _repoDivision = new(Context);

            _docenteVM.Divisiones = _repoDivision.GetDivisiones();
            if (User.IsInRole("Administrador"))
                _docenteVM.Roles = _repo.GetAllRoles();
            else
                _docenteVM.Roles = _repo.GetRolDocente();
            _repo.Validar(_docenteVM);
            if(!_repo.Success)
            {
                foreach (var _error in _repo.Error)
                    ModelState.AddModelError("", _error);
                return View(_docenteVM);
            }
            else
            {
                _docenteVM.Usuario.Contrasena = _docenteVM.Usuario.NumeroControl;
                _docenteVM.Usuario.CorreoElectronico = _docenteVM.Usuario.NumeroControl + "@rcarbonifera.tecnm.mx";
                _repo.Agregar(_docenteVM);
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Editar(int _id)
        {
            DocenteViewModel _docenteVM = new();
            DocentesRepository _repo = new(Context);
            DivisionesRepository _repoDivision = new(Context);

            _docenteVM.Divisiones = _repoDivision.GetDivisiones();
            if (User.IsInRole("Administrador"))
                _docenteVM.Roles = _repo.GetAllRoles();
            else
                _docenteVM.Roles = Context.Roles.Where(r => r.Rol == "Docente");
            _docenteVM.Usuario = _repo.GetDocenteById(_id);
            if (_docenteVM == null)
                return RedirectToAction("Index");
            return View(_docenteVM);
        }
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public IActionResult Editar(DocenteViewModel _docenteVM)
        {
            DocentesRepository _repo = new(Context);
            DivisionesRepository _repoDivision = new(Context);

            _docenteVM.Divisiones = _repoDivision.GetDivisiones();
            var _entity = Context.Usuarios.FirstOrDefault(u => u.Id == _docenteVM.Usuario.Id);
            _repo.Validar(_docenteVM);
            if (_repo.Success != true)
            {
                foreach (var _error in _repo.Error)
                    ModelState.AddModelError("", _error);
                return View(_docenteVM);
            }
            else
            {
                _entity.NumeroControl = _docenteVM.Usuario.NumeroControl;
                _entity.Nombre = _docenteVM.Usuario.Nombre;
                _entity.Contrasena = _docenteVM.Usuario.NumeroControl;
                _entity.CorreoElectronico = _docenteVM.Usuario.NumeroControl + "@rcarbonifera.tecnm.mx";
                _entity.IdDivision = _docenteVM.Usuario.IdDivision;
                _entity.IdRol = _docenteVM.Usuario.IdRol;
                _repo.Editar(_entity);
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles ="Administrador")]
        public IActionResult Eliminar(int _id)
        {
            DocentesRepository _repo = new(Context);

            var _entity = _repo.GetDocenteByIdWithIdRolNaviagation(_id);
            if (_entity == null)
                return RedirectToAction("Index");
            if (_entity.IdRolNavigation.Rol == "Jefe Departamento")
                ModelState.AddModelError("", "No puede eliminar al usuario porque es jefe de una división.");
            return View(_entity);
        }
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public IActionResult Eliminar(Usuario _usuario)
        {
            DocentesRepository _repo = new(Context);

            var _entity = _repo.GetDocenteByIdWithIdRolNaviagation(_usuario.Id);
            if (_entity == null)
                ModelState.AddModelError("", "No se ha encontrado el usuario ó ya ha sido eliminado.");
            else
            {
                if (_entity.IdRolNavigation.Rol == "Jefe Departamento")
                    return RedirectToAction("Index");
                else
                {
                    _repo.Eliminar(_entity);
                    return RedirectToAction("Index");
                }
            }
            return View(_usuario);
        }
    }
}

SistemaPracticasAcademicas/Areas/Admin/Views/Docentes/Agregar.cshtml
@model SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels.DocenteViewModel
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" method="post" action="~/Admin/Docentes/Agregar">
            <h1>Agregar Docente</h1>
            <select required asp-for="Usuario.IdDivision" asp-items="@(new SelectList(Model.Divisiones, "Id","Nombre"))">
                <option selected value="">Seleccionar División</option>
            </select>
            <select required asp-for="Usuario.IdRol" asp-items="@(new SelectList(Model.Roles,"Id","Rol"))">
                <option selected value="">Seleccionar Rol</option>
            </select>
            <input type="text" placeholder="Número Control" class="input" maxlength="5" asp-for="Usuario.NumeroControl" id="nControl"/>
            <input type="text" placeholder="Nombre" class="input" asp-for="Usuario.Nombre"/>
            <p id="msgError" class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons">
                <input type="submit" class="btnAceptar" value="ACEPTAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Docentes';">CANCELAR</button>
            </div>
        </form>
    </div>
</section>

SistemaPracticasAcademicas/Areas/Admin/Views/Docentes/Editar.cshtml
@model SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels.DocenteViewModel
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" method="post" action="~/Admin/Docentes/Editar">
            <h1>Editar Docente</h1>
            <select required asp-for="Usuario.IdDivision" asp-items="@(new SelectList(Model.Divisiones, "Id","Nombre"))">
                <option selected value="">Seleccionar División</option>
            </select>
            <select required asp-for="Usuario.IdRol" asp-items="@(new SelectList(Model.Roles,"Id","Rol"))">
                <option selected value="">Seleccionar Rol</option>
            </select>
            <input type="hidden" asp-for="Usuario.Id" />
            <input type="text" placeholder="Número Control" class="input" maxlength="5" asp-for="Usuario.NumeroControl" id="nControl"/>
            <input type="text" placeholder="Nombre" class="input" asp-for="Usuario.Nombre"/>
            <p id="msgError" class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons">
                <input type="submit" class="btnAceptar" value="GUARDAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Docentes';">CANCELAR</button>
            </div>
        </form>
    </div>
</section>

SistemaPracticasAcademicas/Areas/Admin/Views/Docentes/Eliminar.cshtml
@model SistemaPracticasAcademicas.Models.Usuario
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" action="~/Admin/Docentes/Eliminar" method="post">
            @if (Model.IdRol == 2)
            {
            <input type="hidden" name="Id" value="@Model.Id" />
            <h1>@Html.ValidationSummary()</h1>
            <div class="btn-si-no">
                <button type="button" style="margin:10em auto;" class="btnAceptar" onclick="window.location.href='/Admin/Docentes';">ACEPTAR</button>
            </div>
            }
            else
            {
            <input type="hidden" name="Id" value="@Model.Id" />
            <h1>¿Está seguro que desea eliminar al @Model.IdRolNavigation.Rol @Model.Nombre?</h1>
            <p class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons">
                <input type="submit" class="btnAceptar" value="ACEPTAR">
                <button type="button"  class="btnCancelar" onclick="window.location.href='/Admin/Docentes';">CANCELAR</button>
            </div>
            }
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Docentes/Index.cshtml
@model IEnumerable<SistemaPracticasAcademicas.Models.Usuario>
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="guardar">
        <div class="wrapper">
            <div class="searchBox">
                <form asp-controller="Docentes" asp-action="Index" method="post">
                    <input type="text" placeholder="Buscar por nombre o departamento..." title="Escriba un nombre" name="buscar"/>
                    <button type="submit">
                        <ion-icon name="search"></ion-icon>
                    </button>
                </form>
            </div>
             <form action="~/Admin/Docentes/Agregar">
                 <button type="submit" class="btnAgregar"><ion-icon name="add"></ion-icon></button>
             </form>
         </div>
    </div>
    <div class="scrollable">
        <table class="styled-table" id="styled-table">
            <thead>
                <tr>
                    <th>Clave</th>
                    <th>Nombre</th>
                    <th>Departamento</th>
                    <th>Rol</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                @foreach (var docente in Model)
                {
                    <tr>
                        <td>@docente.NumeroControl</td>
                        <td style="text-align:left;">@docente.Nombre</td>
                        <td style="text-align:left;">@docente.IdDivisionNavigation.Nombre</td>
                        <td style="text-align:left;">@docente.IdRolNavigation.Rol</td>
                        <td>
                            <a href="~/Admin/Docentes/Editar/@docente.Id">
                                <ion-icon name="create"></ion-icon>
                            </a>
                        </td>
                        <td>
                            <a href="~/Admin/Docentes/Eliminar/@docente.Id">
                                <ion-icon name="trash" style="color:#CF2A27;"></ion-icon>
                            </a>
                        </td>
                    </tr>
                  }
        </table>
    </div>
</section>