SistemaPracticasAcademicas/Models/Asignatura.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaPracticasAcademicas.Models
{
    public partial class Asignatura
    {
        public Asignatura()
        {
            Practicas = new HashSet<Practica>();
        }

        public int Id { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Practica> Practicas { get; set; }
    }
}

SistemaPracticasAcademicas/Areas/Admin/Controllers/AsignaturasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SistemaPracticasAcademicas.Areas.Repository;
using SistemaPracticasAcademicas.Models;
using System.Linq;
using System.Text.RegularExpressions;

namespace SistemaPracticasAcademicas.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AsignaturasController : Controller
    {
        public AsignaturasController(sistema_academicoContext _context)
        {
            Context = _context;
        }
        public sistema_academicoContext Context { get; }
        public IActionResult Index(string id)
        {
            AsignaturasRepository _repo = new(Context);

            var _entity = _repo.GetAsignaturas();
            if (string.IsNullOrEmpty(id))
                return View(_entity);
            else
                return View(_entity.Where(n=>n.Nombre.ToUpper().Contains(id.ToUpper())));
        }
        [Authorize(Roles ="Administrador")]
        public IActionResult Agregar()
        {
            return View(new Asignatura());
        }
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public IActionResult Agregar(Asignatura _asignatura)
        {
            AsignaturasRepository _repo = new(Context);

            _repo.Validar(_asignatura);
            if(!_repo.Success)
            {
                foreach (var _error in _repo.Error)
                    ModelState.AddModelError("", _error);
                return View(_asignatura);
            }
            else
            {
                _repo.Agregar(_asignatura);
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Editar(int _id)
        {
            AsignaturasRepository _repo = new(Context);

            var _entity = _repo.GetAsignaturaById(_id);
            if (_entity == null)
                return RedirectToAction("Index");
            return View(_entity);
        }
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public IActionResult Editar(Asignatura _asignatura)
        {
            AsignaturasRepository _repo = new(Context);

            var _entity = _repo.GetAsignaturaById(_asignatura.Id);
            if (_entity == null)
                ModelState.AddModelError("", "La asignatura no se ha encontrado ó ya fue eliminada.");
            else
            {
                _repo.Validar(_asignatura);
                if(!_repo.Success)
                {
                    foreach (var _error in _repo.Error)
                        ModelState.AddModelError("", _error);
                    return View(_asignatura);
                }
                else
                {
                    _entity.Clave = _asignatura.Clave;
                    _entity.Nombre = _asignatura.Nombre;
                    _repo.Editar(_entity);
                    return RedirectToAction("Index");
                }
            }
            return View(_asignatura);
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Eliminar(int _id)
        {
            AsignaturasRepository _repo = new(Context);

            var entity = _repo.GetAsignaturaById(_id);
            if (entity == null)
            {
                return RedirectToAction("Index");
            }
            return View(entity);
        }
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public IActionResult Eliminar(Asignatura _asignatura)
        {
            AsignaturasRepository _repo = new AsignaturasRepository(Context);

            var _entity = _repo.GetAsignaturaById(_asignatura.Id);
            if (_entity == null)
            {
                ModelState.AddModelError("", "La asignatura no se ha encontrado ó ya fue eliminada.");
                return View(_asignatura);
            }
            else
            {
                _repo.Eliminar(_entity);
                return RedirectToAction("Index");
            }
        }
    }
}

SistemaPracticasAcademicas/Areas/Admin/Views/Asignaturas/Agregar.cshtml
@model SistemaPracticasAcademicas.Models.Asignatura
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" method="post" action="~/Admin/Asignaturas/Agregar">
            <h1>Agregar Asignatura</h1>
            <input type="text" maxlength="7" placeholder="Clave" name="Clave"/>
            <input type="text" placeholder="Nombre" name="Nombre" />
            <p>@Html.ValidationSummary()</p>
            <div class="buttons">
                <input type="submit" class="btnAceptar" value="ACEPTAR" />
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Asignaturas'">CANCELAR</button>
            </div>
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Asignaturas/Editar.cshtml
@model SistemaPracticasAcademicas.Models.Asignatura
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" action="~/Admin/Asignaturas/Editar" method="post">
            <h1>Editar Asignatura</h1>
            <input type="hidden" name="Id" value="@Model.Id" />
            <input type="text" class="input" name="Clave" value="@Model.Clave" maxlength="7"/>
            <input type="text" class="input" name="Nombre" value="@Model.Nombre" />
            <p class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons">
                <input type="submit" class="btnAceptar" value="GUARDAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Asignaturas'">CANCELAR</button>
            </div>
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Asignaturas/Eliminar.cshtml
@model SistemaPracticasAcademicas.Models.Asignatura
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" action="~/Admin/Asignaturas/Eliminar" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h1>¿Está seguro que desea eliminar la asignatura '@Model.Nombre' con clave: @Model.Clave?</h1>
            <p class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons">
                <input type="submit" class="btnAceptar" Value="ACEPTAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Asignaturas'">CANCELAR</button>
            </div>
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Asignaturas/Index.cshtml
@model IEnumerable<SistemaPracticasAcademicas.Models.Asignatura>
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="guardar">   
        <div class="wrapper">
                <div class="searchBox">
                    <form asp-controller="Asignaturas" asp-action="Index" method="post">
                        <input type="text" placeholder="Buscar por nombre..." title="Escriba un nombre" name="id">
                        <button type="submit">
                            <ion-icon name="search"></ion-icon>
                        </button>
                    </form>
                </div>
                <form action="~/Admin/Asignaturas/Agregar">
                    <button type="submit" class="btnAgregar"><ion-icon name="add"></ion-icon></button>
                </form>
        </div>      
    </div>
    <div class="scrollable">
        <table class="styled-table" id="styled-table">
            <thead>
                <tr>
                    <th>Clave</th>
                    <th>Nombre</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var asignatura in Model)
            {
                <tr>
                    <td>@asignatura.Clave</td>
                    <td style="text-align:left;">@asignatura.Nombre</td>
                    <td style="text-align:left;">
                        <a href="~/Admin/Asignaturas/Editar/@asignatura.Id">
                            <ion-icon name="create"></ion-icon>
                        </a>
                    </td>
                    <td style="text-align:left;">
                        <a href="~/Admin/Asignaturas/Eliminar/@asignatura.Id">
                           <ion-icon name="trash" style="color:#CF2A27;"></ion-icon>
                        </a>
                    </td>
                </tr>
            }
        </table>
    </div> 
</section>