SistemaPracticasAcademicas/Areas/Admin/Models/ViewModels/PracticasViewModel.cs
using SistemaPracticasAcademicas.Models;
using System.Collections.Generic;

namespace SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels
{
    public class PracticasViewModel
    {
        public Practica Practica { get; set; }
        public IEnumerable<Asignatura> Asignaturas { get; set;}
    }
}

SistemaPracticasAcademicas/Models/Practica.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaPracticasAcademicas.Models
{
    public partial class Practica
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Tema { get; set; }
        public string NombreUnidad { get; set; }
        public int NumUnidad { get; set; }
        public string Planteamiento { get; set; }
        public string Periodo { get; set; }
        public string Objetivo { get; set; }
        public string Resultado { get; set; }
        public ulong? Activo { get; set; }
        public int IdAsignatura { get; set; }
        public int IdUsuario { get; set; }

        public virtual Asignatura IdAsignaturaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}

SistemaPracticasAcademicas/Areas/Admin/Controllers/PracticasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels;
using SistemaPracticasAcademicas.Areas.Repository;
using SistemaPracticasAcademicas.Models;
using System;
using System.Linq;

namespace SistemaPracticasAcademicas.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class PracticasController : Controller
    {
        public sistema_academicoContext Context { get; }

        public PracticasController(sistema_academicoContext _context)
        {
            Context = _context;
        }
        public IActionResult Index(string buscar)
        {
            PracticasRepository _repo = new(Context);
            var _entity = _repo.GetAllPracticasWithRelacion();
            if (string.IsNullOrWhiteSpace(buscar))
                return View(_entity);
            else
                return View(_repo.SearchPracticaByString(_entity, buscar));
        }
        public IActionResult Agregar()
        {
            PracticasViewModel _practicaVM = new();
            AsignaturasRepository _repo = new(Context);

            _practicaVM.Asignaturas = _repo.GetAsignaturas();
            return View(_practicaVM);
        }
        [HttpPost]
        public IActionResult Agregar(PracticasViewModel _practicaVM)
        {
            PracticasRepository _repo = new(Context);
            AsignaturasRepository _repoAsignatura = new(Context);

            var _docente = Context.Usuarios.SingleOrDefault(u => u.Nombre == User.Identity.Name);

            _practicaVM.Asignaturas = _repoAsignatura.GetAsignaturas();
            _repo.Validar(_practicaVM);
            if (!_repo.Success)
            {
                foreach (var _error in _repo.Error)
                    ModelState.AddModelError("", _error);
                return View(_practicaVM);
            }
            else
            {
                _practicaVM.Practica.Activo = 1;
                _practicaVM.Practica.IdUsuario = _docente.Id;
               _repo.Agregar(_practicaVM);
                return RedirectToAction("Index");
            }
        }
        public IActionResult Editar(int _id)
        {
            PracticasViewModel _practicaVM = new();
            PracticasRepository _repo = new(Context);
            AsignaturasRepository _repoAsignatura = new(Context);

            _practicaVM.Asignaturas = _repoAsignatura.GetAsignaturas();
            _practicaVM.Practica = _repo.GetPracticaByidWithRelacion(_id);
            if (_practicaVM == null)
                return RedirectToAction("Index");
            return View(_practicaVM);
        }
        [HttpPost]
        public IActionResult Editar(PracticasViewModel _practicaVM)
        {
            PracticasRepository _repo = new(Context);
            AsignaturasRepository _repoAsignatura = new(Context);

            var _docente = Context.Usuarios.SingleOrDefault(u => u.Nombre == User.Identity.Name);
            _practicaVM.Asignaturas = _repoAsignatura.GetAsignaturas();
            var _entity = _repo.GetPracticaByidWithRelacion(_practicaVM.Practica.Id);
            if (_entity == null)
                ModelState.AddModelError("", "No se ha encontrado la práctica ó ya ha sido eliminada.");
            if (_entity.IdUsuarioNavigation.IdDivision == _docente.IdDivision)
            {
                _repo.Validar(_practicaVM);
                if (!_repo.Success)
                {
                    foreach (var _error in _repo.Error)
                        ModelState.AddModelError("", _error);
                    return View(_practicaVM);
                }
                else
                {
                    _entity.Activo = 1;
                    _entity.Nombre = _practicaVM.Practica.Nombre;
                    _entity.NombreUnidad = _practicaVM.Practica.NombreUnidad;
                    _entity.NumUnidad = _practicaVM.Practica.NumUnidad;
                    _entity.Tema = _practicaVM.Practica.Tema;
                    _entity.Planteamiento = _practicaVM.Practica.Planteamiento;
                    _entity.Objetivo = _practicaVM.Practica.Objetivo;
                    _entity.Periodo = _practicaVM.Practica.Periodo + $"{DateTime.Today.Year}";
                    _entity.Resultado = _practicaVM.Practica.Resultado;
                    _repo.Editar(_entity);
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "No puede editar una práctica que no pertenece a su división.");
                return View(_practicaVM);
            }
            
        }
        public IActionResult Eliminar(int _id)
        {
            PracticasRepository _repo = new(Context);

            var _entity = _repo.GetPracticaByidWithRelacion(_id);
            if (_entity == null)
                return RedirectToAction("Index");
            return View(_entity);
        }
        [HttpPost]
        public IActionResult Eliminar(Practica _practica)
        {
            PracticasRepository _repo = new(Context);

            var _docente = Context.Usuarios.SingleOrDefault(u => u.Nombre == User.Identity.Name);
            var _entity = _repo.GetPracticaByidWithRelacion(_practica.Id);
            if (_entity == null)
                ModelState.AddModelError("", "No se ha encontrado la práctica o ya ha sido eliminada.");
            else
            {
                if (_entity.IdUsuarioNavigation.IdDivision == _docente.IdDivision)
                {
                    _entity.Activo = 0;
                    _repo.Editar(_entity);
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError("", "No puede eliminar una práctica que no pertenece a su división");
            }
            return View(_practica);
        }
        public IActionResult EliminarFisica(int _id)
        {
            PracticasRepository _repo = new(Context);

            var _entity = _repo.GetPracticaById(_id);
            if (_entity == null)
                return RedirectToAction("Index");
            return View(_entity);
        }
        [HttpPost]
        public IActionResult EliminarFisica(Practica _practica)
        {
            PracticasRepository _repo = new(Context);

            var _entity = _repo.GetPracticaById(_practica.Id);
            if (_entity == null)
                ModelState.AddModelError("", "No se ha encontrado la practica o ya ha sido eliminada.");
            else
            {
                _repo.Eliminar(_entity);
                return RedirectToAction("Inactivas");
            }
            return View(_practica);
        }
        public IActionResult Ver(int _id)
        {
            PracticasRepository _repo = new(Context);

            var _entity = _repo.GetPracticaByidWithRelacion(_id);
            if (_entity==null)
                return RedirectToAction("Index");
            return new ViewAsPdf(_entity);
        }
    }
}

SistemaPracticasAcademicas/Areas/Admin/Views/Practicas/Activar.cshtml
@model SistemaPracticasAcademicas.Models.Practica
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="head">
        <h1>Activar</h1>
    </div>
    <div class="div">
        <form action="~/Admin/Practicas/Activar" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h2>¿Está seguro que desea volver a activar la práctica: @Model.Nombre?</h2>
            <p class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="btn-si-no">
                <button type="submit">Sí</button>
                <button type="button" onclick="window.location.href='/Admin/Practicas'">No</button>
            </div>
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Practicas/Agregar.cshtml
@model SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels.PracticasViewModel
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable" style="overflow-y:auto;">
        <form class="modal-form" method="post" action="~/Admin/Practicas/Agregar">
            <h1>Agregar Práctica</h1> 
            <div class="grid">
                <div class="c1">
                    <select required asp-for="Practica.IdAsignatura" asp-items="@(new SelectList(Model.Asignaturas,"Id","Nombre"))">
                         <option selected value="">Seleccionar Asignatura</option>
                    </select></div>
                <div class="c2">
                    <select asp-for="Practica.Periodo">
                         <option value="Febrero - Junio">Febrero - Junio</option>
                         <option value="Agosto - Diciembre">Agosto - Diciembre</option>
                    </select>
                </div>
                <div class="c3">
                     <input type="number" asp-for="Practica.NumUnidad" placeholder="N. Unidad"/>
                </div>
            </div>
            <input type="text" asp-for="Practica.NombreUnidad" placeholder="Nombre Unidad"/>
            <input type="text" class="input" asp-for="Practica.Tema" placeholder="Tema"/>
            <input type="text" class="input" asp-for="Practica.Nombre" placeholder="Nombre"/>
            <input type="text" asp-for="Practica.Planteamiento" placeholder="Planteamiento"/>
            <input type="text" asp-for="Practica.Objetivo" placeholder="Objetivo"/>
            <input type="text" asp-for="Practica.Resultado" placeholder="Resultado"/>
            <p id="msgError" class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons-practica">
                <input type="submit" class="btnAceptar" value="ACEPTAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Practicas';">CANCELAR</button>
            </div>
        </form>
    </div>
</section>

SistemaPracticasAcademicas/Areas/Admin/Views/Practicas/Editar.cshtml
@model SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels.PracticasViewModel
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable" style="overflow-y:auto;">
        <form class="modal-form" method="post" action="~/Admin/Practicas/Editar">
            <h1>Editar Práctica</h1> 
            <div class="grid">
                <div class="c1">
                    <select required asp-for="Practica.IdAsignatura" asp-items="@(new SelectList(Model.Asignaturas,"Id","Nombre"))">
                         <option selected value="">Seleccionar Asignatura</option>
                    </select></div>
                <div class="c2">
                    <select asp-for="Practica.Periodo">
                         <option value="Febrero - Junio">Febrero - Junio</option>
                         <option value="Agosto - Diciembre">Agosto - Diciembre</option>
                    </select>
                </div>
                <div class="c3">
                     <input type="number" asp-for="Practica.NumUnidad" placeholder="N. Unidad"/>
                </div>
            </div>
            <input type="hidden" asp-for="Practica.Id" />
            <input type="text" asp-for="Practica.NombreUnidad" placeholder="Nombre Unidad"/>
            <input type="text" class="input" asp-for="Practica.Tema" placeholder="Tema"/>
            <input type="text" class="input" asp-for="Practica.Nombre" placeholder="Nombre"/>
            <input type="text" asp-for="Practica.Planteamiento" placeholder="Planteamiento"/>
            <input type="text" asp-for="Practica.Objetivo" placeholder="Objetivo"/>
            <input type="text" asp-for="Practica.Resultado" placeholder="Resultado"/>
            <p id="msgError" class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons-practica">
                <input type="submit" class="btnAceptar" value="GUARDAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Practicas';">CANCELAR</button>
            </div>
        </form>
    </div>
</section>

SistemaPracticasAcademicas/Areas/Admin/Views/Practicas/Eliminar.cshtml
@model SistemaPracticasAcademicas.Models.Practica
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" action="~/Admin/Practicas/Eliminar" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h1>¿Está seguro que desea eliminar la práctica '@Model.Nombre'?</h1>
            <p class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons">
                <input type="submit" class="btnAceptar" value="ACEPTAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Practicas';">CANCELAR</button>
            </div>
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Practicas/EliminarFisica.cshtml
@model SistemaPracticasAcademicas.Models.Practica
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="head">
        <h1>Eliminar</h1>
    </div>
    <div class="div">
        <form action="~/Admin/Practicas/EliminarFisica" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h2>¿Está seguro que desea eliminar permanentemente la práctica: @Model.Nombre?</h2>
            <p class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="btn-si-no">
                <button type="submit">Sí</button>
                <button type="button" onclick="window.location.href='/Admin/Practicas';">No</button>
            </div>
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Practicas/Inactivas.cshtml
@model IEnumerable<SistemaPracticasAcademicas.Models.Practica>
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <table class="styled-table" id="styled-table">
            <thead>
                <tr>
                    <th>Docente</th>
                    <th>Periodo</th>
                    <th>Titulo</th>
                    <th>Asignatura</th>
                    <th>Unidad</th>
                    <th>Objetivo</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.IdUsuarioNavigation.Nombre</td>
                    <td>@p.Periodo</td>
                    <td>@p.Tema</td>
                    <td>@p.IdAsignaturaNavigation.Nombre</td>
                    <td>@p.NumUnidad</td>
                    <td>@p.Objetivo</td>
                    <td>
                        <a href="~/Admin/Practicas/Ver/@p.Id" target="_blank">
                            <span class="material-icons"><ion-icon name="eye"></ion-icon></span>
                        </a>
                    </td>
                    <td>
                        <a href="~/Admin/Practicas/Activar/@p.Id">
                            <span class="material-icons"><ion-icon name="hammer"></ion-icon></span>
                        </a>
                    </td>
                    <td>
                        <a href="~/Admin/Practicas/EliminarFisica/@p.Id">
                            <span class="material-icons" id="seliminar"><ion-icon name="trash-bin"></ion-icon></span>
                        </a>
                    </td>
                </tr>
            }
        </table>
    </div>
</section>  
<script>

SistemaPracticasAcademicas/Areas/Admin/Views/Practicas/Index.cshtml
@model IEnumerable<SistemaPracticasAcademicas.Models.Practica>
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="guardar">   
        <div class="wrapper">
            <div class="searchBox">
                <form asp-controller="Practicas" asp-action="Index" method="post">
                    <input type="text" placeholder="Buscar por título, docente, asignatura o periodo..." title="Escriba un nombre" name="buscar" />
                    <button type="submit">
                        <ion-icon name="search"></ion-icon>
                    </button>
                </form>
            </div>
            <form action="~/Admin/Practicas/Agregar">
                <button type="submit" class="btnAgregar"><ion-icon name="add"></ion-icon></button>
            </form>
        </div>      
    </div>
    <div class="scrollable">
        <table class="styled-table" id="styled-table">
            <thead>
                <tr>
                    <th>Docente</th>
                    <th>Periodo</th>
                    <th>Título</th>
                    <th>Asignatura</th>
                    <th>Unidad</th>
                    <th>Objetivo</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.IdUsuarioNavigation.Nombre</td>
                    <td style="text-align:left;">@p.Periodo</td>
                    @if(@p.Tema.Length > 30)
                    {
                        <td style="text-align:left;">@(p.Tema.Substring(0, 30)+"...")</td>
                    }
                    else
                    {
                        <td style="text-align:left;">@p.Tema</td>
                    }
                    <td style="text-align:left;">@p.IdAsignaturaNavigation.Nombre</td>
                    <td>@p.NumUnidad</td>
                    @if(@p.Objetivo.Length > 42)
                    {
                        <td style="text-align:left;">@(p.Objetivo.Substring(0, 42)+"...")</td>
                    }
                    else
                    {
                        <td style="text-align:left;">@p.Objetivo</td>
                    }
                    <td>
                        <a href="~/Admin/Practicas/Ver/@p.Id" target="_blank">
                            <ion-icon name="eye"></ion-icon>
                        </a>
                    </td>
                    <td>
                        <a href="~/Admin/Practicas/Editar/@p.Id">
                            <ion-icon name="create"></ion-icon>
                        </a>
                    </td>
                    <td>
                        <a href="~/Admin/Practicas/Eliminar/@p.Id">
                            <ion-icon name="trash" style="color:#CF2A27;"></ion-icon>
                        </a>
                    </td>
                </tr>
            }
        </table>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Practicas/Ver.cshtml
@model SistemaPracticasAcademicas.Models.Practica
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/pdf.css">
    <title>@Model.Nombre</title>
</head>
<body>
    <div class="encabezado">
        <p class="titulo-Encabezado">INSTITUTO TECNOLÓGICO DE ESTUDIOS SUPERIORESDE LA REGIÓN CARBONÍFERA</p>
        <img src="https://www.itesrc.edu.mx/logos/logo_TRANSP_web.png" class="logotec" />
        <p class="formato">Formato de práctica</p>
    </div>
        <div class="nombrePractica2">
        <div style="width:22em;">
            <p class="descripcion">NOMBRE UNIDAD:</p>
            <p class="bold">@Model.NombreUnidad</p>
        </div>
        <div>
            <p class="descripcion">MATERIA:</p>
            <p class="bold">@Model.IdAsignaturaNavigation.Nombre</p>
        </div>
        <div style="width:5em; border-right:none;">
            <p class="descripcion">FECHA:</p>
            <p class="bold">@DateTime.Now.ToShortDateString()</p>
        </div>
    </div>
    <div class="nombrePractica">
        <div>
            <p class="descripcion">NOMBRE:</p>
            <p class="bold">@Model.Nombre</p>
        </div>
        <div>
            <p class="descripcion">TEMA:</p>
            <p class="bold">@Model.Tema</p>
        </div>
        <div style="width:6em;">
            <p class="descripcion">UNIDAD:</p>
            <p class="bold">@Model.NumUnidad</p>
        </div>
        <div style="width:10em; border-right:none;">
            <p class="descripcion">PERIODO:</p>
            <p class="bold">@Model.Periodo</p>
        </div>
        </div>

    <div class="objetivos">
        <p class="descripcion">OBJETIVOS:</p>
        <p class="bold">@Model.Objetivo</p>
    </div>
    <div class="planteamiento">
        <p class="descripcion">PLANTEAMIENTOS:</p>
        <p class="bold">@Model.Planteamiento.Replace(". ",". \n\n")</p>
    </div>
    <div class="resultados">
        <p class="descripcion">RESULTADOS ESPERADOS:</p>
        <p class="bold">@Model.Resultado</p>
    </div>
    <footer>
        <p class="descripcion">Elaborado por: @Model.IdUsuarioNavigation.Nombre</p>
    </footer>
</body>
</html>