SistemaPracticasAcademicas/Areas/Admin/Controllers/DivisionesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels;
using SistemaPracticasAcademicas.Areas.Repository;
using SistemaPracticasAcademicas.Models;
using System.Linq;
using System.Text.RegularExpressions;

namespace SistemaPracticasAcademicas.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrador")]
    public class DivisionesController : Controller
    {
        public DivisionesController(sistema_academicoContext _context)
        {
            Context = _context;
        }
        public sistema_academicoContext Context { get; }
        public IActionResult Index(string id)
        {
            DivisionesRepository _repo = new(Context);

            var _entity = _repo.GetDivisionesWithIdJefeNavigation();
            if (string.IsNullOrWhiteSpace(id))
                return View(_entity);
            else
                return View(_entity.Where(n => n.Nombre.ToUpper().Contains(id.ToUpper())));
        }
        public IActionResult Agregar()
        {
            DivisionViewModel _docenteVM = new();
            DivisionesRepository _repo = new(Context);

            _docenteVM.Docentes = _repo.GetAllJefeDepartamento();
            return View(_docenteVM);
        }
        [HttpPost]
        public IActionResult Agregar(DivisionViewModel _divisionVM)
        {
            DivisionesRepository _repo = new(Context);

            _divisionVM.Docentes = _repo.GetAllJefeDepartamento();
            _repo.Validar(_divisionVM);
            if (!_repo.Success)
            {
                foreach (var _error in _repo.Error)
                    ModelState.AddModelError("", _error);
                return View(_divisionVM);
            }
            else
            {
                _repo.Agregar(_divisionVM);
                return RedirectToAction("Index");
            }
        }
        public IActionResult Editar(int _id)
        {
            DivisionViewModel _divisionVM = new();
            DivisionesRepository _repo = new(Context);

            _divisionVM.Docentes = _repo.GetAllJefeDepartamento();
            _divisionVM.Divisiones = _repo.GetDivisionById(_id);

            if (_divisionVM == null)
                return RedirectToAction("Index");
            return View(_divisionVM);
        }
        [HttpPost]
        public IActionResult Editar(DivisionViewModel _divisionVM)
        {
            DivisionesRepository _repo = new(Context);

            _divisionVM.Docentes = _repo.GetAllJefeDepartamento();
            var _division = _repo.GetDivisionById(_divisionVM.Divisiones.Id);
            if (_division == null)
                ModelState.AddModelError("", "No se ha encontrado la division ó ya ha sido eliminada.");
            else
            {
                _repo.Validar(_divisionVM);
                if (!_repo.Success)
                {
                    foreach (var _error in _repo.Error)
                        ModelState.AddModelError("", _error);
                    return View(_divisionVM);
                }
                else
                {
                    _division.Clave = _divisionVM.Divisiones.Clave;
                    _division.Nombre = _divisionVM.Divisiones.Nombre;
                    _division.IdJefe = _divisionVM.Divisiones.IdJefe;
                    _repo.Editar(_division);
                    _repo.Save();
                    return RedirectToAction("Index");
                }
            }
            return View(_divisionVM);
        }
        public IActionResult Eliminar(int _id)
        {
            DivisionesRepository _repo = new(Context);

            var _entity = _repo.GetDivisionById(_id);
            if (_entity == null)
                return RedirectToAction("Index");
            return View(_entity);
        }
        [HttpPost]
        public IActionResult Eliminar(Division _division)
        {
            DivisionesRepository _repo = new(Context);

            var _entity = _repo.GetDivisionById(_division.Id);
            if (_entity == null)
                ModelState.AddModelError("", "No se ha encontrado la división ó ya ha sido eliminada.");
            else
            {
                _repo.Elminar(_entity);
                return RedirectToAction("Index");
            }
            return View(_division);
        }
    }
}

SistemaPracticasAcademicas/Areas/Admin/Views/Divisiones/Agregar.cshtml
@model SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels.DivisionViewModel
@{ Layout = "AdminLayout";}
<section class="content">
        <div class="scrollable">
            <form class="modal-form" method="post">
                <h1>Agregar División</h1>
                <select required asp-for="Divisiones.IdJefe" asp-items="@(new SelectList(Model.Docentes,"Id","Nombre"))">
                    <option selected value="">Seleccionar Jefe de División</option>
                </select>
                <input type="text" class="input" placeholder="Clave" asp-for="Divisiones.Clave" maxlength="1"/>
                <input type="text" class="input" placeholder="Nombre" asp-for="Divisiones.Nombre"/>
                <p class="msgError">
                    @Html.ValidationSummary()
                </p>
                <div class="buttons">
                <input type="submit" class="btnAceptar" value="ACEPTAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Divisiones';">CANCELAR</button>
            </div>
            </form>
        </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Divisiones/Editar.cshtml
@model SistemaPracticasAcademicas.Areas.Admin.Models.ViewModels.DivisionViewModel
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" method="post" action="~/Admin/Divisiones/Editar">
            <h1>Editar División</h1>
            <select required asp-for="Divisiones.IdJefe" asp-items="@(new SelectList(Model.Docentes,"Id","Nombre"))">
                <option selected value="">Seleccionar Personal</option>
            </select>
            <input type="hidden" asp-for="Divisiones.Id" />
            <input type="text" class="input" asp-for="Divisiones.Clave" />
            <input type="text" class="input" asp-for="Divisiones.Nombre" />
            <p id="msgError" class="msgError">
                @Html.ValidationSummary()
            </p>
           <div class="buttons">
                <input type="submit" class="btnAceptar" value="GUARDAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Divisiones'">CANCELAR</button>
            </div>
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Divisiones/Eliminar.cshtml
@model SistemaPracticasAcademicas.Models.Division
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="scrollable">
        <form class="modal-form" action="~/Admin/Divisiones/Eliminar" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h1>¿Está seguro que desea eliminar la división '@Model.Nombre'?</h1>
            <p class="msgError">
                @Html.ValidationSummary()
            </p>
            <div class="buttons">
                <input type="submit" class="btnAceptar" value="ACEPTAR"/>
                <button type="button" class="btnCancelar" onclick="window.location.href='/Admin/Divisiones';">CANCELAR</button>
            </div>
        </form>
    </div>
</section>  

SistemaPracticasAcademicas/Areas/Admin/Views/Divisiones/Index.cshtml
@model IEnumerable<SistemaPracticasAcademicas.Models.Division>
@{ Layout = "AdminLayout";}
<section class="content">
    <div class="guardar">   
        <div class="wrapper">
            <div class="searchBox">
                <form asp-controller="Divisiones" asp-action="Index" method="post">
                    <input type="text" placeholder="Buscar por nombre..." name="id"/>
                    <button type="submit">
                        <ion-icon name="search"></ion-icon>
                    </button>
                </form>
            </div>
            <form action="~/Admin/Divisiones/Agregar">
                <button type="submit" class="btnAgregar"><ion-icon name="add"></ion-icon></button>
            </form>
        </div>      
    </div>
    <div class="scrollable">
        <table class="styled-table" id="styled-table">
            <thead>
                <tr>
                    <th>Clave</th>
                    <th>Nombre</th>
                    <th>Jefe Carrera</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var division in Model)
            {
                <tr>
                    <td>@division.Clave</td>
                    <td style="text-align:left;">@division.Nombre</td>
                    <td style="text-align:left;">@division.IdJefeNavigation.Nombre</td>
                    <td>
                        <a href="~/Admin/Divisiones/Editar/@division.Id">
                            <ion-icon name="create"></ion-icon>
                        </a>
                    </td>
                    <td>
                        <a href="~/Admin/Divisiones/Eliminar/@division.Id">
                            <ion-icon name="trash" style="color:#CF2A27;"></ion-icon>
                        </a>
                    </td>
                </tr>
            }
        </table>
    </div> 
</section>